name: Tag and Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
    tag-version:
        name: Tag with v<version>
        runs-on: ubuntu-latest
        steps:
          - name: Checkout full history
            uses: actions/checkout@v4
            with:
              fetch-depth: 0  # required to create and push tags
    
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'
    
          - name: Install Hatch
            run: pip install hatch
    
          - name: Get version
            id: get_version
            run: |
              version=$(hatch version)
              echo "version=$version" >> $GITHUB_OUTPUT
    
          - uses: actions/checkout@master
          - name: Bump version and push tag
            uses: laputansoft/github-tag-action@v4.6
            with:
              github_token: ${{ secrets.GH_PAT }}
              tag: "v${{ steps.get_version.outputs.version }}"
              release_branches: main

    publish:
      name: Build and Publish to PyPI
      runs-on: ubuntu-latest
      needs: tag-version
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install build tools
          run: |
            python -m pip install --upgrade pip
            pip install build twine

        - name: Build package
          run: python -m build

        - name: Publish to PyPI with Twine
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          run: twine upload dist/*
