name: CI_Test_Lint_Deploy

on:
  pull_request:
    branches: [ main ]

jobs: 

  validate_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

  check-version:
    name: Ensure version bump
    runs-on: ubuntu-latest
    needs: validate_dependencies
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need history to compare with main

      - name: Get version on PR branch
        id: pr_version
        run: |
          version=$(grep '__version__' vinyl_tracker/__init__.py | cut -d '"' -f2)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get version on main branch
        id: main_version
        run: |
          git fetch origin main
          main_version=$(git show origin/main:vinyl_tracker/__init__.py | grep '__version__' | cut -d '"' -f2)
          echo "version=$main_version" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pip install packaging

      - name: Run version comparison
        run: |
          python scripts/check_version.py \
            "${{ steps.pr_version.outputs.version }}" \
            "${{ steps.main_version.outputs.version }}"

  lint:
    runs-on: ubuntu-latest
    needs: validate_dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install linters
        run: |
          pip install ruff

      - name: Lint Python code
        run: |
          ruff check .
          ruff format .

  test:
    runs-on: ubuntu-latest
    needs: validate_dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: pip install -e .[dev]
      # - run: supabase db start
      # - run: supabase db reset

      - name: Run unit tests
        env:
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
        run: |
          pytest tests/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          pip install build

      - name: Build package
        run: |
          python -m build

  deploy-testpypi:
    name: Publish Dev Package to TestPyPI
    runs-on: ubuntu-latest
    needs: [build, check-version]
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install hatch and twine
        run: pip install hatch twine

      - name: Get dynamic dev version
        id: get_version
        run: |
          base_version=$(hatch version)
          timestamp=$(date +%s)
          dev_version="${base_version}.dev${timestamp}"
          echo "dev_version=$dev_version" >> $GITHUB_ENV
          echo "dev_version=$dev_version" >> $GITHUB_OUTPUT

      - name: Inject dev version into temp package copy
        run: |
          mkdir temp_package
          cp -r vinyl_tracker pyproject.toml README.md temp_package/
          sed -i "s/__version__ = .*/__version__ = \"${{ env.dev_version }}\"/" temp_package/vinyl_tracker/__init__.py

      - name: Build dev package
        working-directory: temp_package
        run: hatch build

      - name: Publish to TestPyPI
        working-directory: temp_package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*