name: Deploy Supabase DB Changes

on:
  push:
    branches: [ main ]

jobs:
  deploy-db:
    name: Deploy Supabase Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Initialise Supabase CLI
        uses: supabase/setup-cli@v1
        with:
            version: latest

      - name: Authenticate with Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase link \
            --project-ref ${{ secrets.PROJECT_REF }} \
            --password $SUPABASE_DB_PASSWORD

      - name: Deploy
        env: 
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase db push \
          --password ${{ secrets.SUPABASE_DB_PASSWORD }} \
      
